### ISSUE TITLE
How to stop sudo-edit?

### ISSUE THREAD

**Issue by ghost** [nflath/sudo-edit#9]
After running sudo-edit, how do I make it stop? How can I open files as my user again?

**Comment by nflath** [comment]
I don't quite understand the issue - I think the best way is to just kill the buffer and reopen the file, though, if I"m understanding properly.

**Comment by ghost** [comment]
I think what I am / was experiencing is an issue with counsel (especially `counsel-find-file`) together with this package. This package breaks counsel completely, especially it's not possible to open a file without sudo-edit anymore, after once launching it.

**Comment by nflath** [comment]
Hmm - I'm not familiar with counsel.

**Comment by articuluxe** [comment]
I think the issue is that once sudo-edit is used to open a file as root, further occurrences of find-file maintain the root prefix. This behavior is reproducible with emacs -Q.  I suppose that may or may not be what the user wants. In general though, since sudo-edit is a separate command, it seems more usable and safe to have find-file open a subsequent file as normal, and require another invocation of sudo-edit if further root access is required. 

Currently to open a subsequent file normally, you have to execute find-file in a buffer wherein buffer-file-name does not have the root prefix. 

The only difference with counsel is that it is not possible to remove the prefix using counsel-find-file, whereas with the default find-file you can at least manually delete the prefix yourself.

**Comment by nflath** [comment]
Hm...the problem, then, is that the actual path to the file does include the sudo - I'm not sure how to fix this, although I'm open to suggestions how.  This only applies to the buffer you opened with sudo-edit, correct?

**Comment by bmalehorn** [comment]
This issue bothers me too. Would it be acceptable to have `sudo-edit` *toggle* sudo on the file?

If so, I'd be willing to write up the CR.

**Comment by nflath** [comment]
I'd be fine with sudo-edit-current-file toggling sudo.
